### ISSUE TITLE
Kpt function "configPath" cannot find files in subdirectories 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#2346] opened 2021-06-27 23:21 UTC
### Expected behavior

configPath (and --fn-config flag) can find files in both current directory ./fn-config.yaml and subdirectories ./*/fn-config.yaml 

### Actual behavior

configPath can only accept path in current directory. When specified a subdirectory:
- --fn-config in `kpt fn eval` gives "error: missing function config file: config/search-replace.yaml" 
- `.pipeline.mutators[n].configPath` gives error  
```yaml
Kptfile is invalid:
Field: `pipeline.mutators[0].configPath`
Value: "config/search-replace.yaml"
Reason: functionConfig must exist in the current package
```

#### To reproduce `kpt fn render`
1. Create a `search-replace.yaml` file as the following content and put it under a subdirectory `config/search-replace.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: resize
data:
  by-path: spec.replicas
  by-value: "3"
  put-value: "5"
```
2. Update the `Kptfile` as below:
```yaml
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: declarative-kpt
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.1
      configPath: config/search-replace.yaml
```
3. add a sample deployment.yaml in current directory
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: nginx
          image: "gcr.io/nginx:1.14.2"
```
4. run `kpt fn render . `

#### To reproduce `kpt fn eval`
run `kpt fn eval --image=gcr.io/kpt-fn/search-replace:v0.1 --fn-config=config/search-replace.yaml`

#### A workable configPath

By moving `config/search-replace.yaml` to current directory, both declarative and imperative kpt fn work.

```bash
mv config/search-replace.yaml .
kpt fn eval --image=gcr.io/kpt-fn/search-replace:v0.1 --fn-config=search-replace.yaml
[RUNNING] "gcr.io/kpt-fn/search-replace:v0.1"
[PASS] "gcr.io/kpt-fn/search-replace:v0.1"
```

**Comment by yuwenma** [comment] 2021-06-27 23:24
@droot @mengqiy

**Comment by frankfarzan** [comment] 2021-06-30 21:36
@droot You want packages to be self-contained, so meta resources such as `functionConfig` must be in the same package, not in sub-packages. As a result, you cannot simply any any path here.

**Comment by droot** [comment] 2021-07-02 17:53
Slight correction to what @frankfarzan said above: `kpt fn render` now supports `functionConfig` referring to subdirectories. I added an e2e test to verify this scenario https://github.com/GoogleContainerTools/kpt/pull/2358

@yuwenma Can you pl. verify if `config` subdirectory is not a subpackage ? because if it's a subpackage, its expected behavior as Frank stated above.

And as far as `eval` is concerned, the path is relative to where the command is run.

**Comment by droot** [comment] 2021-07-02 17:55
We also have a test-case to verify `functionConfig` can not refer to subpackage https://github.com/GoogleContainerTools/kpt/tree/main/e2e/testdata/fn-render/fnconfig-cannot-refer-subpkgs
and error message confirms that you are running into that scenario.

**Comment by etefera** [comment] 2021-07-13 17:09
Closing this due to the expected behavior and test case above. Please reopen to discuss further.

**Closed by etefera** 2021-07-13 17:09 UTC
Labels: enhancement, triaged
