### ISSUE TITLE
`gcr.io/kpt-fn/gatekeeper` container image doesn't exist in `latest`

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleContainerTools/kpt#3134] opened 2022-05-11 22:14 UTC
`docker pull gcr.io/kpt-fn/gatekeeper` is giving this error:
```
Error response from daemon: manifest for gcr.io/kpt-fn/gatekeeper:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/kpt-fn/gatekeeper/manifests/latest".
```

Furthermore, apparently `gcr.io/kpt-fn/gatekeeper:v0.2.1` (referenced [here](https://catalog.kpt.dev/gatekeeper/v0.2/gatekeeper-imperative/)) is dated from Nov 22, 2021, is this one updated regulary with `latest`? Same for `gcr.io/kpt-fn/gatekeeper:v0.2`?

**Comment by droot** [comment] 2022-05-12 18:37
@mengqiy can confirm this, but as per my understanding, we deliberately avoid having `:latest` tag and consider it to be a bad practice especially when it comes to managing configuration. kpt users are strongly recommended to use either fully qualified tag (x.y.z) or floating versioned tags (v0.2 like in this case). That is the only way to ensure prevent configuration errors in production (keeping your config immutable).

Note `floating versions` such as `v0.2` are updated whenever associated version is patched.

If users want to try out the latest, we use `:unstable` tag explicitly to indicate that :)

@mengqi I remember we have a doc somewhere that explains this. Worth creating an FAQ entry for this and linking to that doc because I think this is very important topic.

**Comment by mengqiy** [comment] 2022-05-14 01:01
What Sunil said above is correct.
When using `latest` tag, we can't provide any compatibility guarantee.

**Comment by yuwenma** [comment] 2022-05-14 01:21
@mathieu-benoit To answer your question about the latest releasing version.
KRM functions are developed separately and each fn has its own releasing tag. There's no regular release and v0.2.1 it is the latest release. v0.2 and v0.2.1 points to the same hash. Suggest using v0.2.1 for the similar reason as "latest"

i'm going to close this issue since this is expected behavior. Thank you for the awareness @mathieu-benoit!

**Closed** 2022-05-14 01:21 UTC
Labels: bug, documentation, triaged

**Comment by mathieu-benoit** [comment] 2022-05-14 17:23
Gotcha, thanks @droot, @mengqiy and @yuwenma.

Just curious, is there any reason why  `v0.2`/`v0.2.1` (a1c193183dd8) is dated from Nov 22, 2021, while the latest tag `unstable` (0d2243a5b8ab) is from May 12, 2022? Just making sure I understand what you said @yuwenma:
> There's no regular release and v0.2.1 it is the latest release.

**Comment by yuwenma** [comment] 2022-05-14 21:20
"regular" refers to automated daily/weekly/monthly releases. 
"unstable" is like repo's "Main" branch, while the SemVer2 tag is like repo's releasing branch. Fn releases are managed by a unified workflow, but they are implementation details the users don't need to know.  :)
