### ISSUE TITLE
kpt pkg sync / kpt pkg update commands don't update nested Kptfiles

### ISSUE THREAD

**Issue by ashlineldridge** [GoogleContainerTools/kpt#794] opened 2020-07-07 00:57 UTC
When syncing or updating a Kpt package, if that package contains nested packages, the nested package Kptfiles are not updated. This means that if setters were added to the nested packages in the upstream repository they don't get updated in local Kptfiles which means that you can't then call `kpt cfg set` on them. Could you please advise if this is the intended behavior? 🙇

**Comment by prachirp** [comment] 2020-07-07 17:56
cc @phanimarupaka Can you elaborate how setters work with nested packages?

**Comment by ashlineldridge** [comment] 2020-07-23 05:46
@prachirp @phanimarupaka Any update on whether this is a bug? #801 seems similar.

**Comment by phanimarupaka** [comment] 2020-07-24 07:04
@ashlineldridge Hey. As mentioned in our [slack chat](https://app.slack.com/client/T09NY5SBT/C0155NSPJSZ/thread/C0155NSPJSZ-1594141402.084000), we are still figuring out the best UX for nested/composite packages behavior. You will have to update each of the underlying nested packages using _kpt pkg get_  and set them.

If your repositories are public, can you please provide us with the links and I can help you with the set of commands you can run to achieve the task.

**Comment by ashlineldridge** [comment] 2020-07-24 11:28
@phanimarupaka, thanks for following up. The Slack question was more to do with being able to create top-level setters that "flow" down into dependencies during each sync/update. This one felt more like a bug because if setters have been added upstream but the downstream Kptfiles aren't updated the setters aren't usable.

My work project is private but if you are looking for example use cases for the ways users might like to use nested/composite packages to manage GitOps workflows I'd be happy to put together a public sample repository that demonstrates what we are trying to achieve.

**Comment by phanimarupaka** [comment] 2020-07-24 13:53
@ashlineldridge Are you using latest version of kpt ? So you are saying just the kpt PKG update on a standalone project is not pulling setters from upstream kptfile ? Or is it kpt PKG sync which is not pulling nested packages kptfile changes? I can create an example myself and test if you just confirm the commands you used with expected behavior.

**Comment by phanimarupaka** [comment] 2020-07-24 14:45
@ashlineldridge I tried an example and I see the issue now. So the openAPI definitions are being added to Kptfile on _kpt pkg update_ but the setter reference comments are not being added to the resource files correct ? Thanks for pointing this out.

**Comment by ashlineldridge** [comment] 2020-07-25 23:08
@phanimarupaka I've run your example and `kpt pkg update` does update the root Kptfile. I believe that has always worked for me. The behavior I'm describing is slightly different. I've forked your repository and created commits/tags to reproduce using Kpt version 0.31.0.

```
mkdir somedir; cd somedir
kpt pkg get https://github.com/ashlineldridge/cockroachdb.git@v0.3.1 ./
kpt pkg sync cockroachdb
git init && git add . && git commit -am "Initial commit"
kpt cfg list-setters cockroachdb/helloworld/mysql-kustomize
# Note that the package cockroachdb/helloworld/mysql-kustomize has no setter
# named secret-name.

# Edit cockroachdb/Kptfile and change the version of the helloworld dependency from v0.26.1 to v0.26.2
kpt pkg sync cockroachdb
```

Note that the package `cockroachdb/helloworld/mysql-kustomize` still has no setter named `secret-name` even though the upstream package [has that setter](https://github.com/ashlineldridge/kpt/blob/v0.26.2/package-examples/helloworld/mysql-kustomize/Kptfile#L50) in tag v0.26.2. In the upstream package, the `secret-name` setter is defined in `package-examples/helloworld/mysql-kustomize/Kptfile` and is used in:
- `package-examples/helloworld/mysql-kustomize/instance/kustomization.yaml`
- `package-examples/helloworld/mysql-kustomize/upstream/kustomization.yaml`
- `package-examples/helloworld/mysql-kustomize/instance/statefulset.yaml`

But when `cockroachdb` is synced the setter is not present. Strangely, I'm sure that the last time I tested this with an earlier version of Kpt the setter references in the resource files were synced but the Kptfiles weren't. In version v0.31.0 the setter isn't synced in any files.

**Comment by phanimarupaka** [comment] 2020-07-28 01:07
@ashlineldridge Thanks for your fork. I am able to reproduce it. The heading was slightly misleading that update was also not working. I will work on fixing the update part of sync. On a side note, sync is not actively supported currently and so is not documented. But this is a clear bug and will be fixed.

**Comment by phanimarupaka** [comment] 2020-07-29 08:07
@ashlineldridge I tried with another example and it worked fine. Can you try 

`kpt pkg update cockroachdb/helloworld@v0.26.2 --strategy=resource-merge` instead of your last step `kpt pkg sync cockroachdb`. It doesn't work either.

I think this issue is an edge case specific to this repo example. 

This example works:
`mkdir somedir; cd somedir`
`kpt pkg init .`
`kpt pkg sync set git@github.com:phanimarupaka/updateissuerepo.git@v0.1.0 repo --strategy=resource-merge`
`kpt pkg sync .`  # repo package shouldn't have replicas setter
#Edit Kptfile to v0.2.0 
`kpt pkg sync .` // it should contain replicas setter

Can you please try.

**Comment by ashlineldridge** [comment] 2020-07-29 22:19
@phanimarupaka 

> @ashlineldridge I tried with another example and it worked fine. Can you try
>
> kpt pkg update cockroachdb/helloworld@v0.26.2 --strategy=resource-merge > instead of your last step kpt pkg sync cockroachdb. It doesn't work either.

Yep, that doesn't work either (I'm using v0.32.0). See my diff below after running your update command.

```
❯ git diff
diff --git a/cockroachdb/helloworld/Kptfile b/cockroachdb/helloworld/Kptfile
index a483c7c..d1b4018 100644
--- a/cockroachdb/helloworld/Kptfile
+++ b/cockroachdb/helloworld/Kptfile
@@ -5,7 +5,7 @@ metadata:
 upstream:
     type: git
     git:
-        commit: 4ead24dae4617511785969adc841984d1c5b29f8
+        commit: 89380efb1507563feec11a9a4e928736c4a8a2ca
         repo: https://github.com/ashlineldridge/kpt
         directory: /package-examples/helloworld
-        ref: v0.26.1
+        ref: v0.26.2
diff --git a/cockroachdb/helloworld/mysql-kustomize/instance/statefulset.yaml b/cockroachdb/helloworld/mysql-kustomize/instance/statefulset.yaml
index 0655c1c..82f9a00 100644
--- a/cockroachdb/helloworld/mysql-kustomize/instance/statefulset.yaml
+++ b/cockroachdb/helloworld/mysql-kustomize/instance/statefulset.yaml
@@ -26,7 +26,7 @@ spec:
       containers:
       - name: mysql
         args:
-          - --skip-grant-tables=$(SKIP_GRANT_TABLES)
+        - --skip-grant-tables=$(SKIP_GRANT_TABLES)
         env:
         - name: MYSQL_PASSWORD
           valueFrom:
```

> This example works:
> ...
> Can you please try.

I've tried your second example. It's different from the example I provided in that your dependency package (i.e., `updateissuerepo`) doesn't contain a nested Kpt package. But in either case it still doesn't appear to work correctly. The `repo/Kptfile` is updated after the second sync to include the new setter but the resource file (i.e., `repo/temp.yaml`) doesn't include the reference to the new setter. See diff below after running the second sync.

```
❯ git diff
diff --git a/repo/Kptfile b/repo/Kptfile
index 38ba56a..6c99d32 100644
--- a/repo/Kptfile
+++ b/repo/Kptfile
@@ -5,9 +5,16 @@ metadata:
 upstream:
     type: git
     git:
-        commit: fcf61115e76d4f1788b5e28c92cf86974c0b93cf
+        commit: 2ae2ee907c7fa80d1a442a0f02e9aa07f58f12cb
         repo: git@github.com:phanimarupaka/updateissuerepo
         directory: /
-        ref: v0.1.0
+        ref: v0.2.0
 packageMetadata:
     shortDescription: sample description
+openAPI:
+    definitions:
+        io.k8s.cli.setters.replicas:
+            x-k8s-cli:
+                setter:
+                    name: replicas
+                    value: "3"
```

**Comment by phanimarupaka** [comment] 2020-07-31 06:55
Yes. So I see 2 issues here, 
1. Update is not updating the setter comments in the resource files.
2. Sync is not updating nested packages at all.

Will try to find the root cause and fix it in next couple of weeks. Thanks

**Comment by phanimarupaka** [comment] 2020-08-04 22:57
@ashlineldridge The PR above fixes the first part which is a more serious problem with update in general, so that the new upstream comments are updated with simple kpt pkg update --strategy=resource-merge

The second issue is specific to nested packages/Kptfile which kpt doesn't support currently. However, we as it is a complex dependency problem to solve, we would need more time to design and implement it. Will update this issue as we progress.

**Closed** 2020-09-02 20:59 UTC
Labels: area/cfg, area/pkg, bug, p1, size/M, triaged, ux impact
