### ISSUE TITLE
kpt live apply - doesn't work.

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#1924] opened 2021-05-07 17:33 UTC
### Expected behavior
We advertise that kpt live apply takes input from stdin, when attempting this command I get an error

### Actual behavior
```
~/src/kpt/package-examples/helloworld-kustomize » kustomize build . | kpt live apply -
error: argument '-' is not but must be a directory
```

### Steps to reproduce the behavior
build kpt from the latest next commit: 87191859fdef443395741d85e134e5aa1cd0f877

**Comment by mortent** [comment] 2021-05-07 18:07
Duplicate of https://github.com/GoogleContainerTools/kpt/issues/1894.

**Closed by mortent** 2021-05-07 18:07 UTC
Labels: area/live, bug, p1
