### ISSUE TITLE
Apply-as-a-library Umbrella Issue

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#247] opened 2020-02-20 03:47 UTC
- [ ] Make the apply code, including status and prune, available as a go library

**Comment by mikebz** [comment] 2020-12-12 05:27
is this duplicate of #708 since the ResourceGroup can be used as a library?  @seans3

**Comment by mikebz** [comment] 2021-03-31 22:44
looks like a stale issue, closing.  Please re-open if needed.

**Closed by mikebz** 2021-03-31 22:44 UTC
Labels: area/live, triaged
