### ISSUE TITLE
Kpt live failed when the package has CRDs

### ISSUE THREAD

**Issue by nan-yu** [GoogleContainerTools/kpt#305] opened 2020-03-02 22:28 UTC
The package has a CRD and an CR object. Kpt does not know the ordering to apply the resources, it failed to run `kpt live preview <dir>`, but with a misleading error message:
```
error: error applying resources: 

The grouping object template was not found while applying. kpt
live commands require the grouping object template to define
the set of "grouped" objects. An example of a grouping object
template is:

apiVersion: v1
kind: ConfigMap
metadata:
  name: grouping
  labels:
    "cli-utils.sigs.k8s.io/inventory-id": "my-app"

The two requirements for a grouping object template are:

1. It must be a ConfigMap
2. It must contain the "grouping" label:

  cli-utils.sigs.k8s.io/inventory-id: <GROUP-NAME>

When the grouping object template is applied, a specific
grouping object is created, storing the inventory of object
metadata of all objects applied.
```

**Comment by mortent** [comment] 2020-03-30 16:28
This issue has been solved as far as I know. This was caused by us ignoring the error when reading and validating the manifests. It should fail because the cluster doesn't have the actual CRDs installed, but we now print out the correct error message.

Closing this issue.

**Closed by mortent** 2020-03-30 16:28 UTC
Labels: bug
