### ISSUE TITLE
kpt live init should not be an error when re-run

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#984] opened 2020-08-27 19:22 UTC
Why is it an error to re-run `kpt live init` when the namespace hasn't changed?  I would expect it to not change the `inventory-template.yaml` file and move on without an error.  The current behavior makes it harder to write idempotent scripts around `kpt`.
```
$ kpt live init . --inventory-namespace foo
namespace: foo is used for inventory object
Initialized: /home/tmp/inventory-template.yaml
$ kpt live init . --inventory-namespace foo
namespace: foo is used for inventory object
error: inventory object template file already exists: /home/tmp/inventory-template.yaml
```

**Comment by seans3** [comment] 2021-02-01 05:25
Not a bug--working as intended.

Re-running `init` is dangerous, because it would change inventory fields (name, namespace, inventory-id) which are necessary to find the inventory object in the cluster. `kpt live` commands fail catastrophically if objects have been applied, then the subsequent `init` changes any inventory fields for the inventory object. The previously applied objects would be "lost", since we would not be able to retrieve the inventory object in the cluster. The only way to safely run the `kpt live init` command multiple times is if we can guarantee that no objects have been applied using the first inventory object. This is currently not a safe assumption, and we do not have plans to query the cluster during the `init` command.

I'll leave this open for a bit before closing.

**Closed** 2021-05-25 18:55 UTC
Labels: area/live, triaged
