### ISSUE TITLE
apply-setters incorrectly adds setter tags to fields

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#3723] opened 2023-01-11 19:42 UTC
### Expected behavior
The apply-setters function only updates the value of the field targeted by the setter.

### Actual behavior
If the property targeted by the setter is an empty list and the following field does not have an explicit value, the apply-setter function correctly updates the field targeted by the setter, but also incorrectly adds a setter tag to the following property.

### Steps to reproduce the behavior

Package only contains a single resource:
```yaml
apiVersion: v1
kind: MyKind
metadata:
  name: foo
environments: [] # kpt-set: ${env}
foo:
```

The function config is:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-setters-fn-config
data:
  env: |
    - prod
    - dev
```

We run the apply-setters function: `kpt fn eval --image gcr.io/kpt-fn/apply-setters:v0.1.1 --fn-config ./fn-config.yaml`

The result is:
```yaml
apiVersion: v1
kind: MyKind
metadata:
  name: foo
environments: # kpt-set: ${env}
- prod
- dev
foo: # kpt-set: ${env}
```

**Comment by yuwenma** [comment] 2023-01-20 19:53
This is a duplicate of https://github.com/GoogleContainerTools/kpt/issues/1342, which we think can be a good first issue for new contributor.

**Closed by yuwenma** 2023-01-20 19:53 UTC
Labels: bug, area/fn-catalog, triaged
