### ISSUE TITLE
Can't  set dependencies following the doc

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#308] opened 2020-03-02 23:08 UTC
Reproduce:
1. kpt init an empty folder
```bash
kpt pkg init test8/
ls test8/
Kptfile		README.md
```
2. set dependencies using the example from [the kpt doc](https://googlecontainertools.github.io/kpt/pkg/sync.html) 
```bash
kpt pkg sync set  https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-set test8/
Error: failed to read Kptfile -- create one with `kpt pkg init .`: open Kptfile: no such file or directory
```

Modifying the Kptfile with the dependency works.
```yaml
dependencies:
- name: hello-world
  git:
    repo: "https://github.com/GoogleContainerTools/kpt.git"
    directory: "/package-examples/helloworld-set"
    ref: "master"%                     
```
```bash
kpt pkg sync test9/
updating hello-world (test9/hello-world) from master to master
```

**Comment by mortent** [comment] 2020-03-03 18:09
So this is the intended behavior as far as I can tell. The `kpt pkg sync set` command does not accept an argument to specify the local package directory like many of the other commands. Instead, the last argument specifies the name of the destination directory of the dependent package once it is synced. Thus, the command must be run when the current working directory is the root of the package directory.

I can see how this can be confusing. We should consider if this command should also accept an argument to specify the local package directory. At the very least, the documentation needs to be better here.

**Comment by phanimarupaka** [comment] 2020-11-05 21:06
The PR to address this issue is merged. However, we are not planning to expose sync commands to users and as they are not documented, they will be deprecated soon. This functionality will be addressed by https://github.com/GoogleContainerTools/kpt/issues/957

**Closed by phanimarupaka** 2020-11-05 21:07 UTC
Labels: area/pkg, triaged
