### ISSUE TITLE
`pkg update` formats resources

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2002] opened 2021-05-13 20:00 UTC
Following this doc:

https://kpt.dev/book/03-packages/05-updating-a-package

Notice the change to `ms-tag` introduced.

```
diff --git a/Kptfile b/Kptfile
index 557ec29..e8605d7 100644
--- a/Kptfile
+++ b/Kptfile
@@ -7,15 +7,15 @@ upstream:
   git:
     repo: https://github.com/GoogleContainerTools/kpt
     directory: /package-examples/wordpress
-    ref: v0.3
+    ref: v0.4
   updateStrategy: resource-merge
 upstreamLock:
   type: git
   git:
     repo: https://github.com/GoogleContainerTools/kpt
     directory: /package-examples/wordpress
-    ref: package-examples/wordpress/v0.3
-    commit: b09cb61b5c7e9f994ee1b0b8d8d8546e6e690b05
+    ref: package-examples/wordpress/v0.4
+    commit: 8b3fe0e4566530f54dd91fc545875a688871b402
 info:
   emails:
     - kpt-team@google.com
diff --git a/deployment/volume.yaml b/deployment/volume.yaml
index 28b2c4d..d2b3edf 100644
--- a/deployment/volume.yaml
+++ b/deployment/volume.yaml
@@ -20,6 +20,6 @@ metadata: # kpt-merge: /wp-pv-claim
 spec:
   resources:
     requests:
-      storage: 20Gi
+      storage: 30Gi
   accessModes:
     - ReadWriteOnce
diff --git a/mysql/Kptfile b/mysql/Kptfile
index d1d6c96..813527d 100644
--- a/mysql/Kptfile
+++ b/mysql/Kptfile
@@ -11,4 +11,4 @@ pipeline:
     - image: gcr.io/kpt-fn/apply-setters:v0.1
       configMap:
         ms-image: mysql
-        ms-tag: 5.6
+        ms-tag: "5.6"
```

Running `render` afterwards is a NO-OP.

**Comment by mortent** [comment] 2021-05-13 20:06
So I think the problem here is really validation. The value `5.6` is illegal in a `ConfigMap`. All keys and values must be strings, so a value such as `5.6` must be in quotes.

**Comment by frankfarzan** [comment] 2021-05-13 22:42
The real issue is that this change is introduced by `pkg get` but `fn render` doesn't format/validate. This breaks the intended workflow. Once you render a package, no other commands should introduce additional formatting.

**Comment by mortent** [comment] 2021-05-13 22:57
The cause of this is that `kpt fn render` only reads the Kptfile, but doesn't output the result. So any changes that results from roundtripping the Kptfile into the go struct and back to yaml is not covered. 

In this case, reading the Kptfile into the go struct coerces the yaml float value into a string since the type of the ConfigMap property in the Kptfile is `map[string]string`.

**Comment by frankfarzan** [comment] 2021-05-13 23:34
Related to #2003 where `render` doesn't format `Kptfile`.

**Comment by phanimarupaka** [comment] 2021-05-24 04:10
Addressed by 
https://github.com/GoogleContainerTools/kpt/pull/2058
https://github.com/GoogleContainerTools/kpt/pull/2024

**Closed by phanimarupaka** 2021-05-24 04:10 UTC
Labels: area/hydrate, area/pkg, triaged
