### ISSUE TITLE
Unable to use live apply with PersistentVolumes

### ISSUE THREAD

**Issue by neuromantik33** [GoogleContainerTools/kpt#1328] opened 2020-12-31 15:02 UTC
Hello,

I'm testing a package deployment on microk8s with manually created persistent volumes. But when executing `kpt live apply app/ --reconcile-timeout=10s` I get the following output:

```bash
kpt live apply reservation/ --reconcile-timeout=10s
namespace/reservation unchanged
secret/env-secrets configured
secret/registry-network unchanged
service/db unchanged
statefulset.apps/db configured
persistentvolume/data configured
6 resource(s) applied. 0 created, 3 unchanged, 3 configured
statefulset.apps/db is Current: All replicas scheduled as expected. Replicas: 1
persistentvolume/data is Current: Resource is current
namespace/reservation is Current: Resource is current
secret/env-secrets is Current: Resource is always ready
secret/registry-network is Current: Resource is always ready
service/db is Current: Service is ready
persistentvolume/data is Current: Resource is current
persistentvolume/data is Current: Resource is current
persistentvolume/data is Current: Resource is current
persistentvolume/data is Current: Resource is current
persistentvolume/data is Current: Resource is current
Timeout after 10 seconds waiting for 1 out of 6 resources to reach condition AllCurrent:
PersistentVolume/data Unknown
```
However checking the resources everything checks out
```bash
$ kubectl get statefulsets.apps db 
NAME   READY   AGE
db     1/1     69m
$ kubectl get pvc data-db-0 
NAME        STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-db-0   Bound    data     20Gi       RWO                           69m
$ kubectl get pv data 
NAME   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
data   20Gi       RWO            Retain           Bound    reservation/data-db-0                           69m
```
Any help would be much appreciated.

Nicolas

**Comment by mikebz** [comment] 2021-01-07 22:15
@seans3 is this something you can take a look at?

**Comment by seans3** [comment] 2021-01-13 20:39
@neuromantik33 Can you please include the config yaml for all the resources (especially the PersistentVolume). I'm having problems reproducing this.

**Comment by mikebz** [comment] 2021-01-20 23:08
@neuromantik33 not sure if this is still a problem but it seems like we can't repro it locally.  If the problem appears again please share the config and re-open the issue.  Sorry we were not able to help.

**Comment by seans3** [comment] 2021-01-21 22:13
Hi @neuromantik33. One more note. We actually made some more progress on this issue. We believe the problem you are experiencing is because you have added a `namespace` to the `PersistentVolume`. A `PersistentVolume` is always cluster-scoped. A `PersistentVolumeClaim` can be namespaced, but not the `PersistentVolume`. Please let us know if this resolves the issue by closing this issue again.

On another note, `kpt` should be more resilient to these errors and we are working on that separately.

**Comment by seans3** [comment] 2021-01-21 22:15
Here is a stackoverflow thread on this issue:

https://stackoverflow.com/questions/32316178/does-kubernetes-pv-recognize-namespace-when-created-queried-with-kubectl

**Comment by neuromantik33** [comment] 2021-01-22 21:18
Thanks for the info. I forgot that pvs weren't namespaced. I'm working with some legacy microk8s manifests I'm trying to get managed using CI/CD with kpt. 😅

**Closed** 2021-01-22 22:08 UTC
Labels: area/live, customer, norepro
