### ISSUE TITLE
`kpt pkg get`(v0.34.0)  ignores commented resources.

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#1063] opened 2020-09-23 23:48 UTC
* only for v0.34.0.* 

`kpt pkg get https://github.com/yuwenma/sample-app guestbook` fetches the resource but removes the lines that are commented out.

See https://github.com/yuwenma/sample-app/blob/master/config/kpt-validator.yaml#L12
My local guestbook/config/kpt-validator.yaml ends at ln11.

From users' perspective, I want to keep those commented lines and share them via `kpt pkg get`

**Comment by mortent** [comment] 2020-09-25 06:28
Thanks for reporting this. I am able to reproduce and it seems it affects other commands than `kpt pkg get` too. You can fetch the package and maintain the comments by using the `--auto-set=false` flag, but running other commands afterwards (like `kpt cfg fmt`) will remove the comments.

**Comment by mortent** [comment] 2020-09-25 20:06
After a quick investigation, it looks like this is related to how the underlying `gopkg.in/yaml.v3` library.

**Comment by phanimarupaka** [comment] 2020-11-05 21:26
@mortent Can we close this.

**Comment by mortent** [comment] 2020-12-17 19:49
Why are we closing this one? It isn't a high priority, but it seems like an actual bug.

**Comment by phanimarupaka** [comment] 2020-12-17 19:57
Closed as there was no response and assumed it was fixed.  Reopening

**Comment by droot** [comment] 2022-05-27 23:57
Haven't seen this reported on newer version of `kpt` i.e. `v1.0.0-beta+` so closing this.

**Closed by droot** 2022-05-27 23:57 UTC
Labels: bug, area/pkg, p2, triaged
