### ISSUE TITLE
porch should support token auth for git provider

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#3333] opened 2022-06-29 20:21 UTC
This will help us supporting other repository provider such as Gitlab and Bitbucket.

This was reported by a user on kpt slack channel. Here is [the link](https://app.slack.com/client/T09NY5SBT/C0155NSPJSZ/thread/C0155NSPJSZ-1656503769.614559).

**Comment by natasha41575** [comment] 2022-06-29 22:25
Ack, thanks @droot!

**Comment by mortent** [comment] 2022-06-30 04:38
This seems like a duplicate of https://github.com/GoogleContainerTools/kpt/issues/3232

https://github.com/GoogleContainerTools/kpt/pull/3314 sets up a way to use the `Type` field in the secret to specify to porch which auth scheme should be used. We should make sure we decide on one way to do it and follow it consistently as we add new schemes. I'm open to input on whether the one in the PR is the right way to do it.

**Comment by bgrant0607** [comment] 2022-07-22 22:11
Dupe

**Closed by bgrant0607** 2022-07-22 22:11 UTC
Labels: enhancement, area/porch
