### ISSUE TITLE
kpt setters don't work with Kustomize patchesJson6902

### ISSUE THREAD

**Issue by nicksc423** [GoogleContainerTools/kpt#506] opened 2020-04-10 20:23 UTC
We have a Kustomize patch that looks something like 

```
- op: replace
  path: /spec/rules/0/host
  value: app.my.domain.com
- op: replace
  path: /spec/tls/0/hosts/0
  value: app.my.domain.com
```

I am trying to create a setter for the domain name by running the following kpt command: `kpt cfg create-setter ./ appURL app.my.domain.com` but I receive the following error:
```
Error: ingress-patch.yaml: wrong Node Kind for  expected: MappingNode was SequenceNode: value: {- op: replace
  path: /spec/rules/0/host
  value: app.my.domain.com
- op: replace
  path: /spec/tls/0/hosts/0
  value: app.my.domain.com}
```

**Comment by pwittrock** [comment] 2020-04-11 16:55
Does it work if you manually create it?

**Comment by pwittrock** [comment] 2020-04-11 21:53
The issue is that kpt expects yaml files to contain resources, rather than lists.  Other commands such as `kpt cfg fmt` will fail as well:

`kpt cfg fmt .`

Try inlining the patch into the kustomization.yaml under `patches` and see if that resolves the issue.

**Comment by pwittrock** [comment] 2020-04-11 21:54
Closing in favor of #510

**Comment by pwittrock** [comment] 2020-04-11 21:55
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md#inline-patch-for-patchesjson6902

**Closed by pwittrock** 2020-04-11 21:55 UTC

**Comment by denisok** [comment] 2020-05-19 15:27
inline `patch` doesn't work, at least not with all `kubectl` versions:
```
# kubectl kustomize rook-ceph/instance
Error: json: unknown field "patch"

# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-27T12:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-17T12:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jasonmcboyd** [comment] 2020-08-04 15:42
This needs to be reopened. #510 was closed and it doesn't resolve this issue.

**Comment by CurryWurry** [comment] 2020-12-09 08:28
Please reopen. When using Kustomize patches, you can use inline patches, which is a workaround. However, this does not work when you use a ConfigMapGenerator:

`
configMapGenerator:
- name: web-config
  files:
  - properties/application.yml
`
This will throw an error: "wrong Node Kind for  expected: MappingNode was ScalarNode: value"

**Comment by seh** [comment] 2020-12-16 19:07
Using inline patches also doesn't work if you want to inject a setter or substitution into the patch content, since the patch is stated as a string value when specified as an inline patch. _kustomize cfg set_ doesn't look **inside** such strings to find interpolation placeholder comments.

@pwittrock, can you please reopen this issue?

**Comment by msonnleitner** [comment] 2020-12-28 16:14
I was also hitting that issue.
I also don't think that this is resolved, please reopen
