### ISSUE TITLE
[User Request] Validate KptFile substitions and setters

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#550] opened 2020-04-25 01:48 UTC
When more and more substitutions and setters are added to KptFile, it's hard to maintain, dedup and restructure those setters/substs. 

Expected:
1. validate KptFile to make sure no duplicate setters/substituions, no substitutions are used as values in other substitutions (see [issue#549 ](https://github.com/GoogleContainerTools/kpt/issues/549
)for more details) 

2 a structured overview on setters/substitutions usage and relationship. e.g. which setters/substitutions are sharing the same string values.

**Comment by phanimarupaka** [comment] 2020-04-27 03:10
By dedup you mean no 2 setters must contain same value ? The setters are uniquely identified by their name and not by their value. So 2 setters can have same value and is allowed by design. Nested substitutions are not supported currently. So 2 action items I see from this issue is to

1. Print a warning message to the user if the setters do not exist already for a substitution and that it's being created as part of create-subst invocation. Addressed in this PR https://github.com/kubernetes-sigs/kustomize/pull/2419
2. Perform UX research on list-setters and improvise the way of listing setters and substitutions.

**Comment by phanimarupaka** [comment] 2020-05-11 00:58
https://github.com/kubernetes-sigs/kustomize/pull/2439. This PR addresses issue to list structured view of substitutions along with its relation with setters.

https://github.com/kubernetes-sigs/kustomize/pull/2437. This PR prevents setter and substitution from having same name.

**Closed** 2020-05-11 00:59 UTC
Labels: size/M, week/18
