### ISSUE TITLE
kpt fn run corrupts long lines with trailing comment

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#685] opened 2020-06-02 11:53 UTC
kpt v0.27.0

To reproduce execute:

```shell
kpt fn run --image gcr.io/kpt-functions/no-op <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  somekey: '012345678901234567890123456789012345678901234567890123456789012345678901234' # x
EOF
```
The output will be

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    config.kubernetes.io/path: 'configmap_test.yaml'
data:
  somekey: >-
    012345678901234567890123456789012345678901234567890123456789012345678901234# x
```
As you can see the white space before the comment has now become part of the value. If the value is one character shorter the output is not corrupted.

**Comment by phanimarupaka** [comment] 2020-06-02 22:48
@yhrn Ack. Working on it.

**Comment by phanimarupaka** [comment] 2020-06-08 01:12
@yhrn In the output yaml `# x` is still parsed as comment. And the value for `somekey` remains same. Is this creating a problem when you apply resources ? Both seem same in perspective of YAML syntax.

**Comment by phanimarupaka** [comment] 2020-06-08 01:21
@prachirp Can you please take a look. If I source and sink the file, it is not corrupting the file. Only if we pass through [this](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/ts/demo-functions/src/no_op.ts) image it is altering the file.

**Comment by yhrn** [comment] 2020-06-25 07:14
Hi, is there any update on this one?

**Comment by phanimarupaka** [comment] 2020-06-25 17:48
@yhrn Sorry for the delay. We will get the fix rolled out in kpt release next week. Will keep you posted.

**Comment by phanimarupaka** [comment] 2020-06-25 18:20
@prachirp @yhrn I tested it with kpt v0.30.1 and a go function image example. This issue doesn't occur. It only happens with typescript sdks. So we will work on fixing that(io.ts).

**Comment by frankfarzan** [comment] 2020-06-25 19:48
@phanimarupaka can you capture the input and output of the `no-op` function:

```
$ kpt source > in.yaml
$ kpt source | kpt fn run --image gcr.io/kpt-functions/no-op > out.yaml
```

**Comment by frankfarzan** [comment] 2020-06-25 20:03
@pwittrock

**Comment by phanimarupaka** [comment] 2020-06-25 21:54
@yhrn The issue is due to the lineWidth limitation in [js-yaml](https://github.com/nodeca/js-yaml#safedump-object---options-). @prachirp is working on increasing it to 120. This is a work-around to unblock you. 

The root cause is due to friction in handling yaml style formatting in go and ts. We will work on handling them and keep you posted. Thanks for your patience.

**Comment by yhrn** [comment] 2020-06-26 06:44
> @yhrn The issue is due to the lineWidth limitation in [js-yaml](https://github.com/nodeca/js-yaml#safedump-object---options-). @prachirp is working on increasing it to 120. This is a work-around to unblock you.
> 
> The root cause is due to friction in handling yaml style formatting in go and ts. We will work on handling them and keep you posted. Thanks for your patience.

@phanimarupaka So just to clarify, the workaround should mean that it would work for values no longer than 120 characters, i.e. the lineWidth limitation does not include the comment itself? Because in realty that comments are much longer, typically kpt OpenAPI setters/substitutions.

**Comment by frankfarzan** [comment] 2020-06-26 17:43
Root cause here is described in https://github.com/GoogleContainerTools/kpt/issues/766.

The workaround should probably line limits all together, but it's fixing one of the possible causes, not the general problem.

**Comment by prachirp** [comment] 2020-06-26 17:44
Hey @yhrn , thanks for clarifying here. I unset the lineWidth limitation for the workaround now so functions keep arbitrarily long lines.

**Comment by phanimarupaka** [comment] 2020-06-26 21:51
The fix has been merged. This will be released early next week.

https://github.com/kubernetes-sigs/kustomize/pull/2657

**Comment by yhrn** [comment] 2020-07-02 09:14
@phanimarupaka Any news on the release that will include this?

**Comment by phanimarupaka** [comment] 2020-07-03 23:49
@yhrn Our kpt release schedule slipped due to vacation. We will be releasing early next week. I will ping you after that.

@prachirp Is the typescript sdk released ? Can @yhrn be unblocked with that ?

**Comment by prachirp** [comment] 2020-07-04 03:59
Hey @phanimarupaka , @yhrn , yes I released last week. Please update to kpt-functions v0.14.2 to get unblocked.

**Comment by phanimarupaka** [comment] 2020-07-07 22:52
@yhrn We just had a new release v0.31.0. This issue is addressed in that.

**Closed by phanimarupaka** 2020-07-07 22:52 UTC
Labels: area/fn, bug, p0, triaged
