### ISSUE TITLE
Kpt and kustomize json patches don't work

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/kpt#1324] opened 2020-12-29 07:05 UTC
I have created a demo repo which can be used to reproduce this. 

`kpt pkg get https://github.com/msonnleitner/kpttest@kpt-kustomize-patch-issue patch-issue
`
results in 

>kpt pkg get https://github.com/msonnleitner/kpttest@kpt-kustomize-patch-issue patch-issue
fetching package / from https://github.com/msonnleitner/kpttest to patch-issue
error: [ROOT]/kpt-consumer/patch-issue/kustomize/components/cors/add-cors-policy-to-virtual-service.yaml: wrong Node Kind for  expected: MappingNode was SequenceNode: value: {- op: add

This needs to be reopened. #510 was closed and it doesn't resolve this issue.

_Originally posted by @jasonmcboyd in https://github.com/GoogleContainerTools/kpt/issues/506#issuecomment-668672565_

**Comment by mikebz** [comment] 2020-12-29 17:30
@etefera any chance you can take a look at this?

**Comment by natasha41575** [comment] 2021-01-06 22:12
@etefera @mikebz @phanimarupaka this is a duplicate of #1218

**Comment by mikebz** [comment] 2021-01-06 22:50
should we close this issue and possibly add the example from @msonnleitner there?

**Comment by natasha41575** [comment] 2021-01-07 00:42
@etefera had some ideas and is looking into whether or not it's the same underlying issue

**Comment by etefera** [comment] 2021-01-07 00:45
We were able to repro this error and are investigating the best way to go about implementing the missing `SequenceNode` functionality in the `kustomize` repo. 
@msonnleitner In the meantime, would changing the operation in https://github.com/msonnleitner/kpttest/blob/kpt-kustomize-patch-issue/kustomize/components/cors/add-cors-policy-to-virtual-service.yaml to replace and having the entire `http` node as the value suffice for your use case?

**Comment by msonnleitner** [comment] 2021-01-07 08:32
@etefera Well I guess it would not suffice but then I again, I am currently evaluating kpt, so I currently don't need work arounds...

**Comment by seh** [comment] 2021-01-15 14:59
Related: #1342.

**Comment by natasha41575** [comment] 2021-03-01 19:43
@msonnleitner are you still having this issue? I am unable to reproduce this error with the latest release when running kpt pkg get https://github.com/msonnleitner/kpttest@kpt-kustomize-patch-issue patch-issue

**Comment by msonnleitner** [comment] 2021-03-02 09:05
@natasha41575 It seems that it is working now, can't reproduce it with 0.38.

**Closed** 2021-03-10 18:27 UTC
Labels: bug, customer, norepro, triaged
