### ISSUE TITLE
kpt fn sink not writing output to specified directory

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#981] opened 2020-08-27 18:08 UTC
In this example I try to write `kpt fn sink` output to `../tmp` but instead it overwrites the current working directory files.
```
$ mkdir test
$ kpt pkg init test/
writing test/Kptfile
writing test/README.md
$ cd test
$ cp ../helloworld/namespace.yaml .
$ cat namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    color: orange
$ mkdir ../tmp
$ kpt fn source . | kpt fn run .  --image gcr.io/kpt-functions/label-namespace -- label_name=color label_value=blue | kpt fn sink ../tmp
$ cat namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    color: blue
$ ls ../tmp
```

**Comment by mikebz** [comment] 2020-12-11 00:30
@natasha41575 @runewake2 interesting issue for either one of you to explore, repro and potentially fix.  Seems to be a very nicely documented bug report.  Thank you @wpwoodjr

**Comment by runewake2** [comment] 2021-01-15 00:51
Hi,

I believe what is happening is being caused by `kpt fn run` being passed a directory argument. This prevents `kpt fn run` from outputting and being consumed by your `kpt fn sink` command and instead has it perform an in-place operation. Removing the `.` directory argument in `kpt fn run` should allow your `kpt fn source | kpt fn run | kpt fn sink` pipeline to complete as you expect.

For example:

```diff
- kpt fn source . | kpt fn run .  --image gcr.io/kpt-functions/label-namespace -- label_name=color label_value=blue | kpt fn sink ../tmp
+ kpt fn source . | kpt fn run --image gcr.io/kpt-functions/label-namespace -- label_name=color label_value=blue | kpt fn sink ../tmp
```

I've opened PR #1361 that hopefully helps clarify this behavior in kpt's documentation.

If your still encountering this issue after making this change let us know.

**Comment by runewake2** [comment] 2021-01-21 18:32
I'm going to close this issue. If the changes I suggested above don't fix the issue you are encountering please reopen this bug.

**Closed by runewake2** 2021-01-21 18:32 UTC
Labels: area/cfg, p1, size/M, triaged
