### ISSUE TITLE
Can't git checkout the kpt repo on Windows

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#3463] opened 2022-08-15 21:20 UTC
We can't do `git checkout` for the kpt repo on windows: https://github.com/GoogleContainerTools/kpt/runs/7844543379?check_suite_focus=true

There are several files under https://github.com/GoogleContainerTools/kpt/tree/main/package-examples/cert-manager-basic containing `:` in the file name. e.g. https://github.com/GoogleContainerTools/kpt/blob/main/package-examples/cert-manager-basic/cert-manager/role-cert-manager:leaderelection.yaml.
`:` is considered as invalid on Windows. 
Is there a reason why we use `:` as part of the filename? Can we change it to `-` or `_`?

@droot @mortent @justinsb @natasha41575 

Encountered this issue when working on https://github.com/GoogleContainerTools/kpt/pull/3450.

**Comment by natasha41575** [comment] 2022-08-15 21:40
I ran into this issue too when kyaml virtual filesystem also didn't like `:`. I fixed that issue by patching kyaml, but perhaps it would be better to write our packages without `:` to support more general use cases (including windows).

**Comment by justinsb** [comment] 2022-08-17 21:24
I imagine the problem is that it's valid in a k8s object name (or some k8s object names), but we should normalize that before using it as a filesystem name.  I think it's only going to be `:`, but there might be others.

It might also be fun to see what happens if an object is called `aux`: https://www.howtogeek.com/fyi/windows-10-still-wont-let-you-use-these-file-names-reserved-in-1974/

**Comment by rquitales** [comment] 2022-11-03 22:45
This should be fixed by #3487

**Closed by rquitales** 2022-11-03 22:45 UTC
Labels: bug
