### ISSUE TITLE
When kubeconfig points to a private cluster kpt incurs timeout on every command

### ISSUE THREAD

**Issue by ashlineldridge** [GoogleContainerTools/kpt#787] opened 2020-07-02 12:09 UTC
I'm working primarily with private EKS clusters at the moment so my kubeconfig generally points to an API endpoint which isn't directly accessible. After upgrading to 0.30.1, kpt hangs on every command due to its [default behaviour](https://github.com/GoogleContainerTools/kpt/blob/master/internal/util/openapi/openapi.go#L32) of trying to fetch the OpenAPI schema from the cluster before falling back to the built-in schema. This results in a HTTP timeout before swallowing the error.

I guess I'm looking for guidance here more than anything. Is this behavior intended? Should I just alias `kpt` to `kpt --k8s-schema-source "builtin"` and move on?

Really great work on the tool, BTW. Thanks 🙏

**Comment by prachirp** [comment] 2020-07-02 20:49
Hey Ashlin, thanks for reaching out and for the feedback! 🙏 

Yes, this is the intended behavior as described in our reference https://googlecontainertools.github.io/kpt/reference/#openapi-schema
I'm closing this out but please reopen if you have any followup questions.

**Closed by prachirp** 2020-07-02 20:49 UTC
Labels: area/live, triaged

**Comment by ashlineldridge** [comment] 2020-07-02 21:01
Thanks, @prachirp 🙇
