### ISSUE TITLE
kpt alpha rpkg copy fails with sub packages

### ISSUE THREAD

**Issue by henderiw** [GoogleContainerTools/kpt#3607] opened 2022-10-10 20:19 UTC
### Expected behavior

We should be able to cope and create a revision of a package with sub packages 

### Actual behavior

kpt alpha rpkg copy yndd-mgmt-app-packages-1c33ad9ec51ade03f7f275b10a4e44b749767e79 --revision v1 -n default
Error: Internal error occurred: command error on refs/heads/drafts//v1: funny refname

### Information

See above

**Comment by mortent** [comment] 2022-10-11 03:59
Thanks for reporting this. Do you have detailed steps for how to reproduce this? I've tried to use copy on a package that includes a subpackage, and it seems to work for me.

I notice that the error includes a git ref that seems like it is missing the package name: `refs/heads/drafts//v1`. I would expect the format to be `refs/heads/drafts/<packageName>/v1`. I'm not sure how this would happen though.

**Comment by henderiw** [comment] 2022-10-11 04:23
I created a public repo with the package, so I hope you can use it as well

 kpt alpha repo register \
>   --namespace default \
>   https://github.com/henderiw-kpt/test-package.git

kpt alpha rpkg copy test-package-93515d0d1b6dfa9531096f2bc006b5b9617f6807 --revision v1 -n default
Error: Internal error occurred: authentication required

Now I get this error, but the difference might be that the package was private before and now public

**Comment by henderiw** [comment] 2022-10-12 04:31
The package I provided allows to reproduce the issue. It seems that you cannot mix private and public repos in porch.
I made the repo private for the test, but will make it public again so you can access it.

kpt alpha rpkg copy test-package-93515d0d1b6dfa9531096f2bc006b5b9617f6807 --revision v1 -n default
Error: Internal error occurred: command error on refs/heads/drafts//v1: funny refname

**Comment by henderiw** [comment] 2022-10-12 19:17
@mortent Can you reproduce it with this package?

**Comment by mortent** [comment] 2022-10-13 16:20
@henderiw Yeah, I'm seeing the same error as you. I hope to find time to dig into it today.

**Comment by mortent** [comment] 2022-10-13 19:33
So I've done a quick review of this.

The auth error is just because porch doesn't have permissions to update the package in git. The error message definitely has room for improvement.

The `Error: Internal error occurred: command error on refs/heads/drafts//v1: funny refname` issue is because the package in question here is actually at the root of the repository. I think this is a bug, since porch assumes each package lives within a subdirectory of the repository, with the name of the directory being the name of the package. The result is a packagerevision that doesn't belong to a package (i.e. `.spec.packageName` is not set). I'll try to come up with a fix for that. But in general Porch repos should usually just have directories at the root. If you have other use-cases, it would be interesting to understand them better.

But even with this fix, you will almost certainly run into the issue described in https://github.com/GoogleContainerTools/kpt/issues/3599. But it is something that is already a priority for us to fix.

**Comment by henderiw** [comment] 2022-10-14 04:52
ok thx. so I will have to create the uber packages always with a directory in the repo.

kpt alpha rpkg copy test-package-ok-e105b8cb75d54fccc79620b3b110dc95fc45b59c --revision v1 -n default
test-package-ok-f584060f0b21403407944b6ae9d435da2ac3bdd8 created

this worked now

**Comment by mortent** [comment] 2023-01-27 23:38
Closing this. The copy command do still have the issue described in #3599.

**Closed by mortent** 2023-01-27 23:38 UTC
Labels: bug, good first issue, triaged, area/porch
