### ISSUE TITLE
Umbrella: Migrate Kustomize kunstruct to kyaml

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#387] opened 2020-03-17 20:34 UTC

**Comment by bgrant0607** [comment] 2020-04-01 21:35
Should this issue be in https://github.com/kubernetes-sigs/kustomize instead?

**Comment by monopole** [comment] 2020-05-13 19:06
Dupe of https://github.com/GoogleContainerTools/kpt/issues/394
There's no need for a an umbrella at this time

**Closed by monopole** 2020-05-13 19:06 UTC
Labels: cleanup, cmd/kustomize, size/XXL, sprint/2
