### ISSUE TITLE
kpt cfg set very slow due to parsing openapi schema

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1781] opened 2021-04-21 11:48 UTC
### Expected behavior
`kpt cfg set` to be a reasonably fast thing to do

### Actual behavior
```shell
$ echo {} >empty-openapi.json
$ time kpt cfg set pkg/ some-setter "something"
pkg/
set 3 field(s) of setter "some-setter" to value "something"
kpt cfg set pkg/ some-setter "something"      0,95s user 0,03s system 112% cpu 0,863 total
$ time kpt cfg set --k8s-schema-path=empty-openapi.json --k8s-schema-source=file pkg/ some-setter "something"
pkg/
set 3 field(s) of setter "some-setter" to value "something"
kpt cfg set --k8s-schema-path=empty-openapi.json --k8s-schema-so      0,06s user 0,01s system 129% cpu 0,052 total
```
As you can see using an empty OpenAPI schema file speeds it around 15x and the result always seems to be the same.

### Information
kpt version 0.38.1

### Steps to reproduce the behavior
See "Actual behavior" section

**Comment by mikebz** [comment] 2021-04-21 16:26
@natasha41575 can you take a look please?

**Comment by natasha41575** [comment] 2021-04-23 20:26
cc @mortent @phanimarupaka

**Comment by phanimarupaka** [comment] 2021-04-24 22:06
@yhrn Thanks for filing the issue. The issue is with all the kpt commands and not just `kpt cfg set`. The reason being, kpt parses openapi schema before invoking every command. This problem will be addressed as a whole in the upcoming kpt v1.

**Comment by natasha41575** [comment] 2021-04-26 18:29
@yhrn Thank you for bringing this to our attention. To add to @phanimarupaka's comment, there are a couple things I'd like to note.

We will be replacing `kpt cfg set` with a kpt function that will apply all setters at once. There is an example of this function here:
https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/apply-setters/simple

In this scenario, we will only have to parse the schema one time, and the `apply-setters` function will apply multiple setters.  

Using a package with two setters, I've gotten the following result: 

Using the new function: 
```
$ time kpt fn run simple

real	0m1.147s
user	0m0.738s
sys	0m0.058s
```

Using `kpt cfg set`:
```
$ time kpt cfg set . name my-new-name
./
set 1 field(s) of setter "name" to value "my-new-name"

real	0m0.709s
user	0m0.708s
sys	0m0.040s

$ time kpt cfg set .some-key some-value
./
set 1 field(s) of setter "name" to value "my-new-name"

real	0m0.692s
user	0m0.703s
sys	0m0.043s
```

With `kpt cfg set`, the schema needs to be parsed for each setter, but with the new function, the schema only needs to be parsed once for all setters. We are hopeful that this will improve overall performance for your and others' use cases. 

Though parsing the schema is slow, it is useful in some situations for setters (such as looking up the type of the field being set). We will take a look at the cost of parsing the schema in the context of the next version of kpt.

**Comment by yhrn** [comment] 2021-04-27 06:43
@natasha41575 Thanks for the update! I'll try out the new setter fn.

**Comment by yhrn** [comment] 2021-04-27 07:58
@natasha41575 @mortent I tried out the [new setter fn](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/go/apply-setters) and in general it is a massive improvement with both inline interpolation, declarative declaration and the ability to set multiple setter values at once. I saw two problems though:

1. [Blocker] I can't find a way to specify the setter type. The typical case where this breaks is when to set an annotation to the string "true" and it instead because a YAML bool.
2. If providing incomplete setter values for a complex expression the fn will do some kind of best effort attempt at figuring out what the missing value was and calculate the new value using that, e.g. if 'x=value' is provided as input and the expression in `kpt-set: something-${x}-${y}`. This probably works well if there are delimiters between x and y that do not appear in the values but is otherwise likely to yield unexpected results, e.g. for `kpt-set: something-${x}${y}`. I would like to have an option for the fn to error out instead when some but not all values for a complex expression are provided.

I realize this issue might not be the optimal place to report this so feel free to direct me where to put it instead (the kpt-functions-catalog repo does not have issues enabled)

**Comment by phanimarupaka** [comment] 2021-04-27 16:04
@yhrn Thanks for trying out the new apply-setters function and providing the feedback.

1. Providing type information will be addressed in the coming versions of the function. Not just type, we want to provide a way for the package publishers to provide the comprehensive schema for setters so that package consumers can fill them with authoring assistance. That effort is WIP. The futuristic UX would look like this

2. Consider a most common case of ${image}:${tag} setter. It would raise friction if we expect users to provide both image and tag when they want to update just the tag(which is more frequent operation compared to updating image). So making such best effort to derive the values is helpful in most of the cases. I think the problem you are facing is for setters with no delimiters which is ambiguous and not very common. I can make a change to error out in such scenarios where setters are with no delimiters. Does that address your issue ?

**Comment by yhrn** [comment] 2021-04-27 17:18
@phanimarupaka Thanks for a quick response!

1. Great, that addresses my concerns.
2. We do have these more unusual cases so erroring out specifically in those cases when not all setter values are provided would likely be good enough.

**Comment by yhrn** [comment] 2021-04-27 17:19
@phanimarupaka Another question - would it be feasible to move the apply-setter logic out of the main package so that it can be imported and reused in other, complex functions?

**Comment by phanimarupaka** [comment] 2021-04-28 08:04
@yhrn Sure. Added an issue for tracking https://github.com/GoogleContainerTools/kpt/issues/1832

**Comment by natasha41575** [comment] 2021-04-28 18:41
@phanimarupaka can we file a separate issue for apply-setters to error out for setters with no delimiters? 

@yhrn Is there anything else you would like us to address?

**Comment by yhrn** [comment] 2021-04-29 06:23
@natasha41575 Thanks for asking - I have one more question but I opened #1838 to avoid derailing this issue even more.

I think it might make sense to keep this issue open until fully addressed by a released version but it's not that important to me since we have a simple workaround in place.

**Comment by natasha41575** [comment] 2021-04-29 17:39
Thank you for filing follow-up issues. Because `kpt cfg set` is being deprecated, I am going to close this issue as there doesn't appear to be anything else to do here right now. If performance for setters is still slow in the next version of kpt, we can reopen this or open a new issue.

**Closed by natasha41575** 2021-04-29 17:39 UTC
Labels: area/openapi, bug, customer, triaged
