### ISSUE TITLE
Registering an empty repo causes an errors for rkpg

### ISSUE THREAD

**Issue by johnbelamaric** [GoogleContainerTools/kpt#3391] opened 2022-07-20 19:35 UTC
### Expected behavior
An empty repo should be the same as an empty main branch.

### Actual behavior
Porch and kpt alpha rkpg commands get confused if there is an empty repo:

```
jbelamaric@jbelamaric:~/proj/nephio-packages$ kpt alpha rpkg get
Error: branch "main" doesn't exist: reference not found 
```

### Information

kpt 1.0.0-beta.18
Porch 0.0.7

Using CSR with workload identity (though likely it doesn't matter).

### Steps to reproduce the behavior

Create and register an empty Git repository. Run `kpt alpha rpkg get`. The Porch UI shows errors as well.

**Comment by johnbelamaric** [comment] 2022-07-20 19:40
I created a main branch by pushing a README.md file to it, and now it's working.

**Comment by mortent** [comment] 2022-07-25 19:00
This is at least partly intended behavior as described in https://github.com/GoogleContainerTools/kpt/pull/3024. But while we don't want to end up creating the first branch through porch (which makes it the default branch in github), it doesn't seem necessary to error out when we are listing packages.

**Comment by mortent** [comment] 2022-08-30 04:27
This is fixed with https://github.com/GoogleContainerTools/kpt/pull/3472 and https://github.com/GoogleContainerTools/kpt/pull/3473

**Closed by mortent** 2022-08-30 04:27 UTC
Labels: bug, p1, triaged, area/porch
