### ISSUE TITLE
Crash: kpt live apply fails for output table

### ISSUE THREAD

**Issue by neuromantik33** [GoogleContainerTools/kpt#1329] opened 2020-12-31 15:08 UTC
When executing `kpt live apply app/ --reconcile-timeout=10s --output table`, kpt crashes with the following error message:

```bash
$ kpt live apply reservation/ --reconcile-timeout=10s --output table
NAMESPACE   RESOURCE                                  ACTION        STATUS      CONDITIONS                                AGE     MESSAGE                                 
            Namespace/reservation                                   Unknown     -                                         -                                               
reservatio  PersistentVolume/data                                   Unknown     -                                         -                                               
reservatio  Secret/env-secrets                                      Unknown     -                                         -                                               
reservatio  Secret/registry-network                                 Unknown     -                                         -                                               
reservatio  Service/db                                              Unknown     -                                         -                                               
reservatio  StatefulSet/db                                          Unknown     -                                         -                                               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16fcf93]

goroutine 183 [running]:
sigs.k8s.io/cli-utils/cmd/printers/table.(*ResourceStateCollector).processStatusEvent(...)
	/go/pkg/mod/sigs.k8s.io/cli-utils@v0.21.1/cmd/printers/table/collector.go:189
sigs.k8s.io/cli-utils/cmd/printers/table.(*ResourceStateCollector).processEvent(0xc00190a6f0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/sigs.k8s.io/cli-utils@v0.21.1/cmd/printers/table/collector.go:172 +0x173
sigs.k8s.io/cli-utils/cmd/printers/table.(*ResourceStateCollector).Listen.func1(0xc000eeed80, 0xc00303e420, 0xc00190a6f0)
	/go/pkg/mod/sigs.k8s.io/cli-utils@v0.21.1/cmd/printers/table/collector.go:153 +0x145
created by sigs.k8s.io/cli-utils/cmd/printers/table.(*ResourceStateCollector).Listen
	/go/pkg/mod/sigs.k8s.io/cli-utils@v0.21.1/cmd/printers/table/collector.go:150 +0x6c
```
This does not happen when using the default event output however. Could this be related to another issue I've created #1328 ?

Thanks in advance

Nicolas

**Comment by mikebz** [comment] 2021-01-07 17:29
Thank you for reporting.  We'll have someone take a look.

**Comment by seans3** [comment] 2021-01-13 20:40
@neuromantik33 Can you include the config yaml for resources (especially the PersistentVolume). I'm having trouble reproducing this error.

**Comment by seans3** [comment] 2021-01-13 20:49
This appears to be a straighforward nil pointer error. Here is the code:
```
func (r *ResourceStateCollector) processStatusEvent(e event.StatusEvent) {
    if e.Type == event.StatusEventResourceUpdate {
        resource := e.Resource
        previous := r.resourceInfos[resource.Identifier]
        previous.resourceStatus = e.Resource
    }
}
```
The error occurs at the line:
```
        previous.resourceStatus = e.Resource
```
...so it seems clear that `previous` is not found, and when we try to dereference a field from the nil `previous` we get the crash. I will create a fix, but I still can not currently reproduce this error. A reproducible case would give us better confidence in the fix.

**Comment by neuromantik33** [comment] 2021-01-13 22:53
Sure thing.. I'm using kpt to configure a sort of hack to run on microk8s _without_ storage enabled. Here is the entire YAML file
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: reservation # {"$kpt-set":"namespace"}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - args:
        - postgres
        - -c
        - statement_timeout=120000
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        - name: POSTGRES_DB
          value: reservation # {"$kpt-set":"db-name"}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWD
              name: env-secrets
        - name: POSTGRES_USER
          value: reservation # {"$kpt-set":"db-user"}
        image: postgres:12
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 5432
          name: psql
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi # {"$kpt-set":"db-storage"}
      volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: db
  name: data
  namespace: reservation # {"$kpt-set":"namespace"}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi # {"$kpt-set":"db-storage"}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-db-0
    namespace: reservation # {"$kpt-set":"namespace"}
  hostPath:
    path: /tmp/reservation/pg_data # {"$kpt-set":"db-host-path"}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: reservation # {"$kpt-set":"namespace"}
spec:
  ports:
  - name: psql
    port: 5432
    protocol: TCP
    targetPort: psql
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP
```
In order to get it to work, you'll probably have to replace the reference to `env-secrets` for the postgres password env variable.
Hope this helps :) Thanks !

**Comment by mortent** [comment] 2021-01-20 22:30
So this panics because the collector (that keeps track of the latest status for all resources) receives an event pertaining to a resource that it doesn't know about. This is something that shouldn't happen, since we pass the same set of resource identifiers to the poller and the collector. 
The reason this happens in the example, is that the PersistentVolume in the manifest includes a namespace, but it is actually a cluster-scoped resource. So the identifier we create from the object read from the cluster doesn't match the identifier we create from the manifest.
I think we should use the RESTMapper when we compute the identifier to make sure we only include the namespace in the identifier for namespaced resources.

**Comment by neuromantik33** [comment] 2021-01-22 21:16
Thanks for the info :) This is a legacy microk8s set of manifests I've been trying to reconcile with 😅

**Comment by mortent** [comment] 2021-01-26 06:27
@seans3 So it seems like turning an unstructured into an identifier isn't something we can do safely without checking the scope of a resource with the RESTMapper. Resource we read back from the cluster should always have the correct namespace value set, but I'm not sure if it is practical to handle those separately. Ideally it seems like we should pass a RESTMapper into the conversion functions in the `object` package. And we also need to account for situations where a type is not known by the RESTMapper but we have the CRD included in the resources that should be applied.

Any thoughts on how we can best handle this?

**Comment by seans3** [comment] 2021-01-28 18:03
Fixed by: https://github.com/kubernetes-sigs/cli-utils/pull/314

**Closed by seans3** 2021-01-28 18:03 UTC
Labels: area/live, bug, customer, triaged
