### ISSUE TITLE
kpt pkg get does not fail when fetching a non-kpt package

### ISSUE THREAD

**Issue by borismw** [GoogleContainerTools/kpt#2323] opened 2021-06-23 08:49 UTC
When fetching a random directory of a Git-Repository wich does not exist at all kpt tries to fetch, errors but still the directory is created and a Kptfile is generated.

```
kpt pkg get git@github.com:GoogleContainertools/kpt.git/bibbidi-bobbidi-boo
```

### Expected behavior
kpt throws an expressive error message and does not create any files.

especially when using kpt inside a script the results can be very confusing

### Actual behavior
kpt checks out the directory displays an error message but still creates the directory and generates a Kptfile.

```
Package "bibbidi-bobbidi-boo":
Fetching git@github.com:GoogleContainertools/kpt@main
From github.com:GoogleContainertools/kpt
 * branch            main       -> FETCH_HEAD
 + 4bb6d56...2e91ef6 main       -> origin/main  (forced update)
Adding package "bibbidi-bobbidi-boo".
Error: lstat /tmp/kpt-get-159126868/bibbidi-bobbidi-boo: no such file or directory 
```

### Information

```
kpt version
> 1.0.0-alpha.10
```
Package: kpt pkg get git@github.com:GoogleContainertools/kpt.git/bibbidi-bobbidi-boo <- directory does not exist, so no package.

### Steps to reproduce the behavior
As stated above
```
kpt pkg get git@github.com:GoogleContainertools/kpt.git/bibbidi-bobbidi-boo # <- Directory does not exist.
```
**EDIT:** Reformulated the bug since the original report did not describe a bug but expected behavior.

**Comment by frankfarzan** [comment] 2021-06-23 19:06
This is by design, and noted here:

> There is one scenario where a Kptfile is implicit: You can use kpt to fetch any Git directory containing KRM resources, even if it does not contain a Kptfile. Effectively, you are telling kpt to treat that Git directory as a package. kpt automatically creates the Kptfile on the local filesystem to keep track of the upstream repo. This means that kpt is compatible with large corpus of existing Kubernetes configuration stored on Git today!

For example, cockroachdb is just a vanilla directory of KRM:

$ kpt pkg get https://github.com/kubernetes/examples/staging/cockroachdb

https://kpt.dev/book/02-concepts/01-packages


We can potentially consider a "strict mode" configured using a flag passed to `pkg get` to disable this behavior.

**Comment by mikebz** [comment] 2021-06-23 19:15
@borismw can you share with us wether your directory existed?  It seemed like on Slack you mentioned that the directory didn't exist and you didn't get an error.

**Comment by borismw** [comment] 2021-06-24 11:18
> This is by design, and noted here
Thanks, good to know.
> can you share with us wether your directory existed?

Well in the case I mentioned there's not a single yaml file in the directory or its subdirectories. Neither a Kptfile nor a KRM.
```
kpt pkg get git@github.com:GoogleContainertools/kpt.git/mdtogo
```
But I do understand the use-case: You want to be able to fetch any directory making it a KPT package.

Currently you can also do something like this:
```
kpt pkg get git@github.com:GoogleContainertools/kpt.git/bibbidi-bobbidi-boo
```
Even though the upstream-source does not exist kpt creates a subdirectoy _bibbidi-bobbidi-boo_ and generates a Kptfile. Here's the command's output.

```
Package "bibbidi-bobbidi-boo":
Fetching git@github.com:GoogleContainertools/kpt@main
From github.com:GoogleContainertools/kpt
 * branch            main       -> FETCH_HEAD
 + 4bb6d56...2e91ef6 main       -> origin/main  (forced update)
Adding package "bibbidi-bobbidi-boo".
Error: lstat /tmp/kpt-get-159126868/bibbidi-bobbidi-boo: no such file or directory 
```

To be fair: You still get an error message. My mistake was to not check the kpt error code while invoking it in a script. So my script just continued and I wondered what the error was. 

Still I think not even creating a directory would be more explicit in the latter case.

P.S.: I know that the bug title and bug description is a little misleading now as I now de-facto described another case in this comment. If you want me to open a new bug or to refine the description, please let me know. Thanks for your kind and fast response.

**Comment by frankfarzan** [comment] 2021-06-24 17:48
I agree, the following should not be mutating the local filesystem:

```shell
kpt pkg get git@github.com:GoogleContainertools/kpt.git/bibbidi-bobbidi-boo
```

It should fail with an error message that the Git directory doesn't exist (not the cryptic local `tmp` directory).

The `mdtogo` is an interesting one though. kpt can have heuristics (no KRM resource found) to detect when it's likely not what the user intends, although the utility is questionable at this point.

@borismw Does the `strict mode` described above (to mean there should be a Kptfile in the Git directory) solve this general problem for you?

**Comment by borismw** [comment] 2021-06-25 10:13
@frankfarzan I'd leave the wording `strict` up to you but I think it would be very useful to have some kind of fail early mechanism. I understand that you want to achieve ease of use and enable the user to adopt just *any* set of KRMs as a kpt package. I totally agree that the onboarding onto a KPT workflow should be as hassle-free as possible.

But consider you have some scripted solution which checks out some packages programmatically and through a subtle bug you check out the wrong directory and/or the wrong commit hash (so the source of error already has two dimensions) - it's just very hard to debug when kpt just carries on, because it performs not a _get or throw_ but some kind of _get or init_.

Maybe instead of or additional to a flag `--strict` the behavior could be made clear by using different **verbs** - if this'd be not too much of a change. For instance
* `kpt pkg import` - imports whatever you specify and generates a Kptfile if there is none
* `kpt pkg clone` - clones a valid package, fails if there is no Kptfile present - (although I admit this can easily be confused with the behavior of git clone)

Regarding the wording I have no strong feelings one way or the other. But an optional _fail early_ approach would be definitely helpful.

**Comment by mortent** [comment] 2021-06-28 17:45
I think there are a couple of things here:

First, the `kpt pkg get` command is implemented in a very similar way to the update command. So what actually happens is that it will just create the folder and the Kptfile with the `Upstream` section, and then ask the underlying libraries to "reconcile" the package, i.e. upgrade the local fork to match the desired upstream as specified in the Kptfile. This matches the way Kubernetes work with providing the desired state and then have a process that reconciles the actual state to match the desired state. Currently the command doesn't clean up the directory and Kptfile when it fails, which it probably should. 

The reference to the `tmp` package in the error message when specifying a non-existing directory should be improved. We have other situations where we handle this. An example is that if the Kptfile in upstream is the old version, the error message references the repo rather than the temporary directory on local disk.

A flag (like `strict`) sounds reasonable here. I'm not convinced we want to introduce additional commands for this. We just need to make sure we also extend this to the `kpt pkg update` command and any references to subpackages. Presumably using the flag means every independent subpackage should also reference an upstream package with a Kptfile.

**Comment by mikebz** [comment] 2021-06-28 19:01
I have marked this as P2 as it seems like this is a suggestion, @borismw please correct me if I am wrong.  Overall this would be a way to potentially improve things.  My sense is that we might want to wait on more customers to chime in on this UX prior to making CLI updates (as those are notoriously hard to migrate later).

**Closed** 2021-07-29 18:28 UTC
Labels: bug, customer, p2, triaged
