### ISSUE TITLE
fix(fn.kustomize.build): provide git binary for remote ressources execution

### ISSUE THREAD

**Issue by davinkevin** [GoogleContainerTools/kpt#791] opened 2020-07-05 05:13 UTC
Hi, 

I try to use the `kustomize-build' function to create my source, the problem is I use, for simplicity a remote `bases`/`resources` and the image containing the node+kustomize doesn't contain the git binary required by `kustomize` for fetching the assets.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podcast-server-example

resources:
- git::https://gitlab.com/davinkevin/Podcast-Server.git//deployment/kubernetes/base/

configMapGenerator:
- name: podcast-server
  behavior: merge
  literals:
  - "max-update-parallels=15" # {"$ref":"#/definitions/io.k8s.cli.substitutions.max-update-parallels"}
  - "concurrent-download=126" # {"$ref":"#/definitions/io.k8s.cli.substitutions.concurrent-download"}
  - "number-of-day-to-download=31" # {"$ref":"#/definitions/io.k8s.cli.substitutions.number-of-day-to-download"}
  - "number-of-day-to-save-cover=128" # {"$ref":"#/definitions/io.k8s.cli.substitutions.number-of-day-to-save-cover"}

secretGenerator:
- name: podcast-server
  behavior: merge
  literals:
  - database.password=bar
```

The result is: 

```log
apiVersion: v1
kind: ResourceList
metadata:
  name: output
items: []
results:
- message: |
    Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//deployment/kubernetes/base/': evalsymlink failure on '/source/podcast-server/git::https:/gitlab.com/davinkevin/Podcast-Server.git/deployment/kubernetes/base' : lstat /source/podcast-server/git::https:: no such file or directory", loader.New "no 'git' program on path: exec: \"git\": executable file not found in $PATH"
  severity: error
```

I will do a PR to add git in the image BTW

**Comment by prachirp** [comment] 2020-07-06 16:29
Thanks for the fix @davinkevin ! I pushed the new image to gcr.io/kpt-functions/kustomize-build and will add a test so there's no regression. Please close this out after you verify the new image.

**Comment by davinkevin** [comment] 2020-07-08 06:40
Thanks you to for the integration ❤️

I've tested it like you do in the `e2e.sh` and this is working perfectly.

But, I tried to run it through `kpt` with the imperative or declarative way and I end up with the no ouptut or error. Could you provide and example on how to run it in both situation?

If I run it imperatively, I have the following response:
![image](https://user-images.githubusercontent.com/1970922/86884986-bdf93300-c0f4-11ea-8756-4fb56ec960f1.png)

If I run it declaratively, with the following function definition:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |
      container:
        image:  gcr.io/kpt-functions/kustomize-build
        network:
          required: true
data:
  path: /source
```

I have the following result
![image](https://user-images.githubusercontent.com/1970922/86885347-67402900-c0f5-11ea-99b1-6b69a224b059.png)

I've tried a lot of solution, but in fact, I didn't found (or miss) the information about where are mounted the file system inside the docker container when using `kpt`. Due to this, I can't provide kustomize the correct build path. Could you help me on this ?

**Comment by prachirp** [comment] 2020-07-09 18:32
Hey Davin,
Kpt has a --mount flag which accepts the same type, src, dst arguments as docker does to mount the file system inside the container. I think this is similar to a previous issue of kpt not handling source functions. https://github.com/GoogleContainerTools/kpt/issues/587

I only got this working using the exec runtime. I built kustomize build as an executable and ran it in kpt.

```
# Start in kpt-functions-catalog/functions/ts directory
$npm install -g pkg && npm i
...
$ npx pkg dist/kustomize_build_run.js
npx: installed 122 in 6.783s
> pkg@4.4.9
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-linux-x64    [====================] 100%
  fetched-v14.4.0-macos-x64    [====================] 100%
  fetched-v14.4.0-win-x64      [====================] 100%
$ mv kustomize_build_run-macos ~
$
$ cd ~/workspace/test
$
$ kpt pkg get https://github.com/davinkevin/Podcast-Server/deployment/kubernetes/ .
fetching package deployment/kubernetes from https://github.com/davinkevin/Podcast-Server to kubernetes
$ mkdir dockerout
$ docker run -u $(id -u) --mount type=bind,src=$(pwd)/kubernetes/base,dst=/source gcr.io/kpt-functions/kustomize-build -d path=/source | kpt fn sink dockerout
$ mkdir execout
$ kpt fn source kubernetes/base | kpt fn run --enable-exec --exec-path /Users/prachirp/kustomize_build_run-macos -- path=kubernetes/base | kpt fn source | kpt fn sink execout
$ diff -r dockerout execout 
Only in execout: kustomization.yaml
```

**Comment by davinkevin** [comment] 2020-07-10 06:25
Thanks for your very clear answer 👍.

For the original issue, I think this can be close, I let you choose if you prefer to keep it open. 

I will post a message in #587 too to support this fix.

Thank again for your help, support and reactivity ❤️

**Comment by prachirp** [comment] 2020-07-10 15:50
Will close this and work on the root cause issue.

**Closed by prachirp** 2020-07-10 15:50 UTC
Labels: area/fn-catalog, bug, triaged

**Comment by aodinokov** [comment] 2020-07-12 15:35
@davinkevin 
> I've tried a lot of solution, but in fact, I didn't found (or miss) the information about where are mounted the file system inside the docker container when using `kpt`. Due to this, I can't provide kustomize the correct build path. Could you help me on this ?

I've got the same results, and figured out that because of the issue inside kpt, directory that is getting created has a postfix ':ro'.
see more details here: https://github.com/kubernetes-sigs/kustomize/pull/2709
Let's say, you do:
```
kpt fn run ./d --mount type=bind,src=$(pwd)/test/,dst=/source/
```
in that case you can workaround it in you function definition with 
```
data:
  path: '/source/:ro/'
```

I hope this will be merged soon and it will start working without workarounds
