### ISSUE TITLE
kpt apply-setters fails when a value is not set in both Kptfiles

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2365] opened 2021-07-07 03:54 UTC
### Expected behavior

I have a [network](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/networking/network) package which includes a `subnet` subpackage that uses a "prefix" setter.

The "prefix" setter is *only* used in the `subnet` subpackage. I expect to only have to provide it to the `apply-setters` config in the subpackage (or *only* in the parent package).

### Actual behavior

If I don't provide a value for the setter in *both* the parent and subpackage, this error is raised:

```
  Results:
    [ERROR] failed to apply setters: values for setters [${prefix}] must be provided
  Stderr:
    "values for setters [${prefix}] must be providedvalues for setters [${prefix}] must be provided"
    ""
  Exit code: 1
```

### Information

kpt package: https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/networking/network

Downstream issue: https://github.com/GoogleCloudPlatform/blueprints/issues/28

**Comment by phanimarupaka** [comment] 2021-07-07 06:00
@morgante You will have to provide the value in the both places because, there is no delimiter between `prefix` and `network-name` setters. `apply-setters` function tries to do pattern matching in order to derive the values of setters for which the values are not provided(like `prefix`). Since there is no delimiter, it will need the user to provide the default value in both the places. You solved it the correct way by adding the default value in both places. So now, the package consumer can update the value in either of the places and it works fine. If the consumer updates the value in both parent and subpackage, parent package value wins. 

There are no action items for `apply-setters` function in this case. Let me know if you are satisfied with the answer so that I can close the issue.

**Comment by phanimarupaka** [comment] 2021-07-07 06:02
On a different note, you can use [ensure-name-substring](https://catalog.kpt.dev/ensure-name-substring/v0.1/) function in order to achieve the task instead of using setters.

**Comment by morgante** [comment] 2021-07-07 16:38
@phanimarupaka I'm not sure that really answers it—in the cases where `apply-setters` doesn't have the information it needs (in the nested subpackage, or in the parent) I think it should ignore or drop the value.

Specifying the value in both places introduces confusion because the parent package always wins.

**Comment by phanimarupaka** [comment] 2021-07-07 17:05
@morgante That is possible if we can match value with the pattern. for e.g. `foonetwork-name-router-nat # kpt-set: ${prefix}${network-name}-router-nat` if you just specify value for `network-name` setter and not `prefix` setter, `apply-setters` doesn't know what is the existing value of `network-name` setter. So it expects users to provide the value in such ambiguous cases.

**Comment by morgante** [comment] 2021-07-07 17:34
I now see that if I exclude `network-name` *and* `prefix` from the subpackage setters.yaml, everything works properly. Given that I'm satisfied with the current behavior (though do suggest we should document this more somewhere).

**Comment by morgante** [comment] 2021-08-11 23:30
Reopening because this has come up again. Currently, kpt v1 requires setting all the setters for a field at the same level which makes composition harder.

**Comment by phanimarupaka** [comment] 2021-08-12 19:48
@morgante As explained earlier, it is only true for ambiguous strings. Can you elaborate steps to reproduce.

**Comment by phanimarupaka** [comment] 2021-08-24 09:05
@morgante Are there any action items on this issue ? Can we close this and wait for a new issue from WIPE ?

**Closed** 2021-09-22 18:36 UTC
Labels: bug, size/S, p1, area/fn-catalog, customer, triaged
