### ISSUE TITLE
`kpt pkg update` doesn't work from within a package

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1180] opened 2020-11-04 19:50 UTC
This is not shown as a supported flow in --help, but it's expected. We also need to make sure support for relative paths in consistent across all commands (Let's do an audit).

```
$  kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-set@v0.3.0 ./
$  cd helloworld-set
$  kpt pkg update .
```

Output:
```
...
Error: RemoveAll .: invalid argument
```

At the very least, the error message should be improve. Currently it reads as a bug in kpt.

**Comment by phanimarupaka** [comment] 2020-11-05 20:51
https://github.com/GoogleContainerTools/kpt/issues/234 is a duplicate of this issue. Will be tracking it with this issue.

**Comment by phanimarupaka** [comment] 2020-11-05 21:20
https://github.com/GoogleContainerTools/kpt/issues/885 is a duplicate as well.

**Comment by phanimarupaka** [comment] 2021-08-21 23:37
This was in kpt v0. This works fine now in kpt v1.

**Closed by phanimarupaka** 2021-08-21 23:37 UTC
Labels: area/pkg, triaged
