### ISSUE TITLE
kpt live apply: Solve namespace bootstrapping problem

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1810] opened 2021-04-23 22:49 UTC
Currently namespace resource can't be included in the package as inventory object/RG needs it to be created already. The resources in the package can be deployed only after creating inventory object/RG in the cluster. This is a chicken-egg problem due to which creating namespace is part of bootstrapping problem in kpt currently. Consumers must resort to creating namespace. This leads to friction in kpt UX. We should solve this problem.

**Comment by seans3** [comment] 2021-04-26 07:46
I don't believe this is correct. Namespace can be included, since we have special-case code to ensure the namespace for the inventory object is always created before the inventory object. Closing. Please re-open as a bug if you can reproduce a situation where this does not work.

**Closed by seans3** 2021-04-26 07:46 UTC
Labels: area/live, enhancement
