### ISSUE TITLE
When I run `kpt fn render` in a nested project, variables aren't expanded correctly

### ISSUE THREAD

**Issue by moorea7** [GoogleContainerTools/kpt#3795] opened 2023-02-07 23:32 UTC
### Expected behavior

should generate values such as:
```
name: artifactreader-gke-projectname-clustername-001 # kpt-set: artifactreader-gke-${project-id}-${cluster-name}
```

### Actual behavior

actually generating:
``` 
name: artifactreader-gke-projectname-001 # kpt-set: artifactreader-gke-${project-id}-${cluster-name}
```

### Information

1.0.0-beta.24

### Steps to reproduce the behavior

project structure:

config-controllers-test/
 * configs/
   * project-name/
     * clusters/
       * clustername-001/

running at the project-name/ level generates the issue above.
running at the clustername-001/ level the ${cluster-name} correctly populates but ${project-id} is not populated unless it was previously filled by a higher level kpt fn render. 

Work around is `kpt fn render` at the project-name level followed by a run at the lowest level of the tree.

**Comment by yuwenma** [comment] 2023-02-09 22:50
Thanks for filing the issue @moorea7 . We are aware of this issue but do not have the capacity to fix the root cause. One temporary solution I can suggest is to avoid using the same character (in your case it's the dash "-")  in both the setter values and and the concatenating syntax.

I'll close this issue since it is a duplication of #3330. We will update and track the fix there

**Closed by yuwenma** 2023-02-09 22:50 UTC
Labels: bug, area/fn-catalog
