### ISSUE TITLE
ResourceGroup CRD RBAC Roles

### ISSUE THREAD

**Issue by jmcudd** [GoogleContainerTools/kpt#3942] opened 2023-05-04 13:45 UTC
How does kpt determine if the ResourceGroup CRD is installed, does it run `kubectl get crds`  or equivalent API call? I have an issue where when I run `kpt live apply` kpt tries to install the CRD even though it is already installed.
```
$ kpt live apply
installing inventory ResourceGroup CRD.
error: Type ResourceGroup CRD needs update. Please make sure you have the permission to update CRD then run `kpt live install-resource-group`.
 error installing ResourceGroup crd
```
Are there any RBAC roles that have to be applied to provide access to ResourceGroups? I don't see anything in the kpt documentation regarding that.

**Comment by jmcudd** [comment] 2023-05-04 19:25
My thought is to have an RBAC policy like this:

**Comment by mortent** [comment] 2023-05-04 19:50
@jmcudd So kpt normally shouldn't try to install the ResourceGroup CRD on every apply. It does two checks before each apply to make sure the ResourceGroup CRD is available. It first checks whether the correct version of the CRD is available by using discovery. This step seems to pass in your case. Second, it makes sure the actual spec of the CRD is the correct one, which in your case seems to fail and that is the reason why kpt then tries to update the CRD. 

https://github.com/GoogleContainerTools/kpt/blob/f6ce5c9510802420dd2bdf13f45d15990c8dce49/pkg/live/inventoryrg.go#L368

Ideally we probably shouldn't have to do this, but rather rely on only the version of the CRD to make the decision. Do you know if the ResourceGroup CRD was installed with kpt? If you can export the CRD definition for the ResourceGroup CRD and post it here, I can try to figure out why it finds a diff.

**Comment by jmcudd** [comment] 2023-05-05 13:38
Yes the CRD was installed with kpt 1.0.0-beta.30. Unfortunately I can't get you a full copy of the yaml that is applied in the cluster, but I did have my system admin verify that the CRD was applied to the cluster. 
```
$ kpt version
1.0.0-beta.30
$ kpt live install-resource-group
installing inventory ResourceGroup CRD...success
```

I've included a partial snippet of the CRD below.


```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: resourcegroup.kpt.dev
  uid: 55f8ca46-784e-4bff-a0e0-8b08f6954a9c
  resourceVersion: '1151791283'
  generation: 1
  creationTimestamp: '2023-05-03T17:55:42Z'
  ...
```

**Comment by mortent** [comment] 2023-05-10 01:36
@jmcudd Thanks for the snippet. I can see that it using the v1 version of the CRD resource, but I'm not able to tell from this why kpt decides it needs to update the CRD. I understand you might be able to share here, but can you try to check and see if you see a diff between the CRD resource on the cluster and the one embedded in kpt? 

You can get the one on the cluster with `kubectl get crd resourcegroups.kpt.dev -oyaml` and the one embedded in kpt is available at https://github.com/GoogleContainerTools/kpt/blob/f6ce5c9510802420dd2bdf13f45d15990c8dce49/pkg/live/inventoryrg.go#L756. Can you try to diff the `.spec` content of each and see if you see any difference?

I'm not able to reproduce the issue unfortunately. Can you share which cluster you are running on (gke, kind, ..)?

**Comment by jmcudd** [comment] 2023-05-10 01:43
I'm using Openshift 4. I'll see if my administrator can run a diff. I don't have sufficient permissions to run `kubectl get crds`. I think we just need to know the proper RBAC settings to access/modify the ResourceGroups.

**Comment by johnbelamaric** [comment] 2023-05-10 02:01
Ah. If you can’t pull the CRD, then kpt can’t see it and so thinks it needs
to be applied…you will need read on CRDs.

**Comment by mortent** [comment] 2023-05-10 23:23
Yeah, I did a quick check and if I don't have permission to read the CRD, then I am able to reproduce the issue. So you need permission to read CRDs on the cluster.

**Comment by mortent** [comment] 2023-05-18 18:49
I think we consider this one resolved, so I'm closing the issue. Feel free to repoen if needed.

**Closed by mortent** 2023-05-18 18:49 UTC
Labels: question, area/live
